# Generated by Django 4.0 on 2021-12-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textsumm', '0002_alter_quicksummary_output'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualUserDetails',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=1000)),
                ('image', models.CharField(default='null', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SocialUserDetails',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=1000)),
            ],
        ),
    ]
