# Generated by Django 4.0 on 2022-01-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textsumm', '0003_manualuserdetails_socialuserdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='quicksummary',
            name='AudioFileName',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='quicksummary',
            name='AudioSummary',
            field=models.CharField(default='null', max_length=1000000),
        ),
        migrations.AddField(
            model_name='quicksummary',
            name='AudioText',
            field=models.CharField(default='null', max_length=1000000),
        ),
    ]
