# Generated by Django 4.0 on 2022-01-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textsumm', '0004_quicksummary_audiofilename_quicksummary_audiosummary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AudioFileName', models.CharField(default='null', max_length=100)),
                ('AudioText', models.CharField(default='null', max_length=1000000)),
                ('AudioSummary', models.CharField(default='null', max_length=1000000)),
            ],
        ),
        migrations.RemoveField(
            model_name='quicksummary',
            name='AudioFileName',
        ),
        migrations.RemoveField(
            model_name='quicksummary',
            name='AudioSummary',
        ),
        migrations.RemoveField(
            model_name='quicksummary',
            name='AudioText',
        ),
    ]
