# Generated by Django 4.0 on 2022-01-14 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textsumm', '0005_audiosummary_remove_quicksummary_audiofilename_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AudioSummary',
        ),
    ]
