# Generated by Django 4.0 on 2022-01-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textsumm', '0006_delete_audiosummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioSummary',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('AudioFileName', models.CharField(default='null', max_length=100)),
                ('AudioText', models.CharField(default='null', max_length=1000000)),
                ('AudioSummary', models.CharField(default='null', max_length=1000000)),
            ],
        ),
    ]
