# Generated by Django 4.0 on 2022-01-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textsumm', '0007_audiosummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileDetails',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_title', models.CharField(max_length=100)),
                ('date_of_file', models.DateTimeField(auto_now=True)),
                ('folder_id', models.CharField(default='null', max_length=100)),
                ('input_text_or_audio', models.CharField(default='null', max_length=100)),
                ('uploaded_filepath', models.CharField(default='null', max_length=100)),
                ('input_text', models.CharField(max_length=1000000)),
                ('output_text', models.CharField(default='null', max_length=1000000)),
            ],
        ),
        migrations.CreateModel(
            name='FolderDetails',
            fields=[
                ('folder_id', models.AutoField(primary_key=True, serialize=False)),
                ('folder_title', models.CharField(max_length=100)),
                ('uid', models.CharField(max_length=100)),
                ('no_of_files', models.CharField(default='null', max_length=100)),
                ('date_of_folder', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
