# Generated by Django 4.0 on 2022-01-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textsumm', '0008_filedetails_folderdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedetails',
            name='folder_id',
            field=models.CharField(max_length=100),
        ),
    ]
