# Generated by Django 4.0.3 on 2022-04-07 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textsumm', '0009_alter_filedetails_folder_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlSummary',
            fields=[
                ('urlid', models.AutoField(primary_key=True, serialize=False)),
                ('urlAddress', models.CharField(default='null', max_length=100)),
                ('urlTranscript', models.CharField(default='null', max_length=1000000)),
                ('urlSummary', models.CharField(default='null', max_length=1000000)),
            ],
        ),
    ]
