# Generated by Django 4.0.3 on 2022-04-09 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textsumm', '0010_urlsummary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manualuserdetails',
            old_name='mid',
            new_name='uid',
        ),
    ]
