# Generated by Django 4.0.3 on 2022-04-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textsumm', '0011_rename_mid_manualuserdetails_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualuserdetails',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
